### ISSUE TITLE
Add INiTS logo to website

### ISSUE THREAD

**Issue by kariem** [GDGVienna/wtmvienna-site#7] opened 2015-12-28 19:46 UTC
INiTS provides resources to make the event organization possible.

**Comment by helmuthb** [comment] 2015-12-29 11:50
@kariem this is a duplicate of #4 which is already implemented on test site. I will update the logo with the version from Krisz and put it live.

**Closed by helmuthb** 2015-12-29 11:50 UTC

**Comment by kariem** [comment] 2015-12-29 12:20
Sorry, did not look through the previous issues. Thank you!
